#ifndef COZY_INTERPRETER_CONSTANTS_H
#define COZY_INTERPRETER_CONSTANTS_H

#define LINE_LENGTH 100
#define ONP_SEPARATOR ' '
#define MAX_NUMBER_OF_LINES 400
#define NUMBER_OF_LETTERS 26

#endif //COZY_INTERPRETER_CONSTANTS_H
