#ifndef COZY_INTERPRETER_CONSTANTS_H
#define COZY_INTERPRETER_CONSTANTS_H

#define LINE_LENGTH 100
#define ONP_SEPARATOR ' '
#define MAX_NUMBER_OF_LINES 400
#define NUMBER_OF_LETTERS 26
#define CHARACTER_LIMIT 90

typedef int line_str_t[LINE_LENGTH];

#endif //COZY_INTERPRETER_CONSTANTS_H
